# Generated by Django 5.1.1 on 2025-05-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
    ]
